site_name: Shouss's Notes
site_url: https://note.shouss.top
docs_dir: docs
site_dir: site
theme:
  name: material
  language: zh
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: 切换到暗色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: 切换到亮色模式
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight
plugins:
  - search
  - mermaid2
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - attr_list
  - md_in_html
  - toc:
      permalink: true
nav:
  - 首页: index.md
  - CMU 15-445:
    - Query Execution: cmu_15_445/query_execution.md
    - Database Logging: cmu_15_445/data_logging.md
    - Recovery with ARIES: cmu_15_445/recovery_with_aries.md
  - ZJU:
    - 马克思主义基本原理:
      - 期末考试事项: zju/marxism_basic_principles/final_exam.md
    - 经济法:
      - 期末考试事项: zju/economic_law/final_exam.md
    - 数据库系统:
      - 期末总复习: zju/database_system/final_review.md
    - 图像信息处理:
      - 期末重点复习: zju/digital_image_processing/final_review.md
      - 23-24 Fall 试题解析: zju/digital_image_processing/23_24_fall_exam.md
