site_name: Shouss's Notes
site_url: https://note.shouss.top
docs_dir: docs
site_dir: site
theme:
  name: material
  language: zh
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: 切换到暗色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: 切换到亮色模式
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight
plugins:
  - search
  - mermaid2
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - attr_list
  - md_in_html
  - toc:
      permalink: true
nav:
  - 首页: index.md
  - CMU 15-445:
    - Query Execution: query_execution.md
    - Database Logging: data_logging.md
    - Recovery with ARIES: recovery_with_aries.md
  - ZJU:
    - 马克思主义基本原理:
      - 期末考试事项: marxism_final_exam.md
    - 经济法:
      - 期末考试事项: economic_law_final_exam.md
